localFileRoot: ../..

entrypoint:
  specifier: mod.ts

dependencyLayers:
- specifier: '@cloudydeno/kubernetes-apis/core/v1'
- specifier: '@cloudydeno/kubernetes-admission'

runtimeFlags:
- --allow-net
- --allow-read=/run
- --allow-env=WEBHOOK_TLS_DIRECTORY

targets:
  alpine:
    ref: example
    baseRef: denoland/deno:alpine-$DenoVersion
